### ISSUE TITLE
[Feature][배포] 배포 관련 설정값 변경

### ISSUE THREAD

**Issue by KimHJ97** [FC-InnerCircle/icd01-team02-o2o2-be#50]
## 어떤 기능인가요?

> 운영 환경 배포 관련 설정값 변경

## 작업 상세 내용

- [ ] Security 설정
- [ ] 외부 환경 변수 설정

**Comment by KERERCVASD** [comment]
try this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
